{% set version = "0.2.3" %}
{% set name = "knit" %}

package:
    name: {{name}}
    version: {{version}}

source:
  fn: {{name}}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/k/{{name}}/{{name}}-{{ version }}.tar.gz
  sha256: 0086828db168e984f8fc0d8e44de8f656dcbfc859b804b07042b8e78fb66d408
  
build:
  number: 0
  skip: True  # [not linux]

requirements:
    build:
        - python
        - setuptools
        - maven
        - openjdk
    run:
        - python
        - requests
        - py4j

test:
  imports:
    - knit

about:
  home: https://github.com/dask/knit
  license: BSD 3-Clause
  license-family: BSD
  license_file: LICENSE
  summary: Python interface YARN

extra:
  recipe-maintainers:
    - quasiben 
    - martindurant
