travis:
  secure:
    BINSTAR_TOKEN: AnNS5vS/W7GbJoG1U2W7DhdrI8NsjnuFe+p9fPW/0OvbIrv8KmSTw1JLurSZqUJ6YJHYR5VzPW0Po1OQVwhJ/eidKj8GssWiYJtzQVvTSIL894CRBt0yQ0OTrL4trMddkebmDj4sZhqGij4Wwl75VEiuJW/QnPAzYO4dw8mGzaZTNbkL5Qoy4lOOTT1thoMqRnIW8nlAWcA6bqjHVvI4bLPnMFIdm7eOq12ekX6dQiVM5eQLTfZOdZheNo5fgclA4a2rQSB7UvYuJpkA/8XZO97o7NuLrq3k6uBBO0bMzWsKd8whjgmmo/iMRP1+WGKxxhGZVKEgsJMfz+gIOgTGHf4oCeMvVPKR7L9RBTOnBd4EgacbkCO7qswAkJGtz6sbhlI3W7UYiZQ2VVTKMKH0KzR1OF1WOFBLAv4BQlPdbpDebroavSknNXxyNIDEhP7NadAVoKoBjXR7zKibQLhluDyLThXl6M/pT27A/FCEmFmimAW2vqF3apWgwn7iIhceVL6WM9q8Rt7MwOJL+I4163v1hc05RhtbCdcOczYQl+EyBMYkIAdDpPgYOQ5Y+kSU0yeSnfBlKi8GGX3XEhdDa9p1maFOc0GfvG+T0HuuQ6H3ARYvDgSVLTJ/Kf/Yj5u0/Yp8BYvA2ez9d0XspWTRYTcKmLtYrZJeu46qmTUeLh4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
